image: ruby:2.4.2


stages:
#  - build
#  - test
  - review
  - stage
  - production


variables:
 DATABASE_URL: 'mongodb://mongo/user_posts'

#before_script:
# - cd reddit
# - bundle install
# - cd ../

#build_job:
#  stage: build
#  script:
#    - echo 'Building'

#test_unit_job:
##  stage: test
#  script:
#    - echo 'Testing 1'
#    - ruby simpletest.rb
#  services:
#    - mongo:latest

#test_integration_job:
#  stage: test
#  script:
#    - echo 'Testing 2'

#deploy_dev_job:
#  stage: review
#  script:
#    - echo 'Deploy'
#  environment:
#    name: dev
#    url: http://dev.example.com

branch review:
  image: garytrek/ansible_runner
  stage: review
  script:
     - echo "Deploy to $CI_ENVIRONMENT_SLUG"
     - echo "Create server.."
     - cd ./docker/docker-monolith/infra/ansible/
     - echo $GCE_CRED|base64 --decode > gce_cred.json
     - echo $ansible_private_key|base64 --decode > ansible_key && chmod 600 ansible_key
     - ansible-playbook create-env.yml
#     - rm -f ./docker/docker-monolith/infra/ansible/gce_cred.json

  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master


staging:
  stage: stage
  when: manual
  only:
   - /^\d+\.\d+.\d+/
  script:
   - echo 'Deploy'
  environment:
   name: stage
   url: https://beta.example.com


production:
  stage: production
  when: manual
  only:
   - /^\d+\.\d+.\d+/
  script:
   - echo 'Deploy'
  environment:
    name: production
    url: https://example.com


