dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh |
  bash
notifications:
  slack:
    secure: ihXSxj3JvSq1eM1Qh5hk8IuBxMqvgWKPPLIioHdtwotiVb1c9fkY0s6B5OXWrogWX0oTguwnVjnnzI5OD1MGzAoOSZSVIg82+2XOO+l7ialr0cxOdyq5IAz5ObRQwfwxjcGkDrXLq6OwzLqH0/sDYZzJMYyk39dO10KtCdDv9dZ832ZXagiy8AJJWR0PcV0A4Q4AUqOClV+/9u5WVogtm0swz52jRtPyHbDPBhOU/QUsF26S7K8b5DwG3ukonFGJgrooSbD78ogrZTXqOf8jUl9fVsxN6c7rcaKDcYWwwTpZaYWqGZ1GqVOdVsmzMcmziu287Vrbs66f6Bv55hH0Z7PUlzixPgkWse/VTgyC6C7xmcQdfyJZ2xMJI/5CyH/Qw8PGpxJQ7PUnm4KYNN+2rSuoPxOfpAHcc3tJgOxsRODv2MkThqbN6m826X8twqehWfJDqK6dN9BLrx4F0TtcWXptmnEFnzWVrT5FtAwVWSEtT7LV2qEu7Xzl9BLpBWNu1GMFnKMyUVB56mbtxPNaYmwWE0oQPmOLS2secAtIbnuEb0qh8G9CoiE5BJwSTZf8fAcVD1cCkRjAgi+Can2hLngZfm1Prjdg7ByK2pVtN/6QJwcJ6EjVJHv8f8Wio2KuASfOUxvVlBNBVtZ9V7S1oL+2ZNeHyBI1/zRxePWx6F4=
