---
 - name: get and start  my app container
   docker_container:
    name: reddit-app
    image: garytrek/otus-reddit:1.0
    state: started
    restart: yes

 - name:  show started containers for debug
   shell: docker ps
   register: docker_ps

 - debug:
    var: docker_ps.stdout_lines

