---
 - name: install packages to allow apt use https
   apt:
     name: "{{ item }}"
     update_cache: yes
   with_items:
     - apt-transport-https
     - ca-certificates
     - curl
     - software-properties-common

 - name: add docker repo key
   apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

 - name: add docker repo
   apt_repository:
     repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
     state: present

 - name: install docker-ce
   apt:
     name: docker-ce
     state: present

 - name: install pip for docker-py
   apt:
     name: python-pip
     state: present

 - name: install prerequisites  packages for deploy images via ansible
   pip:
     name: docker-py


